### ISSUE TITLE
How to use it without Browserify, simply with bower?

### ISSUE THREAD

**Issue by felippenardi** [goodeggs/angular-cached-resource#89]
I'm trying to add angular-cached-resource to a project with Gulp and without Browserify.

I'm having trouble because of this:
<img width="554" alt="screen shot 2016-06-14 at 11 26 48 am" src="https://cloud.githubusercontent.com/assets/1354492/16058807/8e6fa3d4-3256-11e6-989c-731f0bac47da.png">

The angular-cached-resource is assuming there will be a `module.exports` object, which this project doesn't.

I tried to edit these lines to remove the `if` statement, but then it will fail because my project doen't use `require`.

My question is, is there a minified version I could just import using Bower and start using by simply injecting the dependency to my angular module?

**Comment by felippenardi** [comment]
@demands Would really appreciate your input in this, Max!

**Comment by demands** [comment]
Hi @felippenardi -- try the newest version ([`angular-cached-resource.js`](https://raw.githubusercontent.com/goodeggs/angular-cached-resource/master/angular-cached-resource.js) | [`angular-cached-resource.min.js`](https://raw.githubusercontent.com/goodeggs/angular-cached-resource/master/angular-cached-resource.min.js)).

I think your problem is [solved with this commit](https://github.com/goodeggs/angular-cached-resource/commit/1e89bfa9c4de25298d1984ab61e83975c9672519). Let me know.

**Comment by felippenardi** [comment]
Thanks @demands !!!
